name: nightcore-karaoke

networks:
  project-network:
    name: nightcore-karaoke-network
    driver: bridge

services:
  nightcore-karaoke-bot:
    image: nightcore-karaoke-bot:latest
    container_name: nightcore-karaoke-bot
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          ignore:
            - app/.venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./app/pyproject.toml

    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    restart: on-failure

    volumes:
      - ./src/:/app/src/
      - ./migrations/:/app/migrations/
    networks:
      - project-network

  nightcore-karaoke-db:
    image: postgres:16-alpine
    container_name: nightcore-karaoke-db
    restart: no
    env_file:
      - .env

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - project-network
