"""initial structure

Revision ID: 6df008b066d1
Revises: 
Create Date: 2026-03-10 17:55:58.291162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6df008b066d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guildkaraokeconfig',
    sa.Column('karaoke_host_role_id', sa.BigInteger(), nullable=True),
    sa.Column('karaoke_judge_role_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildpermissionsconfig',
    sa.Column('karaoke_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('karaoke',
    sa.Column('host_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('prizes', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('state', sa.Enum('Анонсировано', 'Идет', 'Завершено', name='karaokestateenum', native_enum=False), nullable=False),
    sa.Column('registration_state', sa.Enum('Открыта', 'Закрыта', name='karaokeregistrationstateenum', native_enum=False), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_karaoke_guild_active', 'karaoke', ['guild_id'], unique=True, postgresql_where=sa.text("state <> 'finished'"))
    op.create_table('staff',
    sa.Column('role', sa.Enum('host', 'judge', name='karaokeroleenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', 'role', name='uq_karaoke_staff_guild_user_role')
    )
    op.create_table('registration',
    sa.Column('karaoke_id', sa.Integer(), nullable=False),
    sa.Column('song_title', sa.String(length=255), nullable=False),
    sa.Column('song_artist', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['karaoke_id'], ['karaoke.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_karaoke_id'), 'registration', ['karaoke_id'], unique=False)
    op.create_index('ix_registration_user_id', 'registration', ['user_id'], unique=False)
    op.create_table('rating',
    sa.Column('karaoke_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('judge_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 10', name='ck_rating_score'),
    sa.ForeignKeyConstraint(['karaoke_id'], ['karaoke.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registration.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_judge_id'), 'rating', ['judge_id'], unique=False)
    op.create_index(op.f('ix_rating_karaoke_id'), 'rating', ['karaoke_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_karaoke_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_judge_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index('ix_registration_user_id', table_name='registration')
    op.drop_index(op.f('ix_registration_karaoke_id'), table_name='registration')
    op.drop_table('registration')
    op.drop_table('staff')
    op.drop_index('uq_karaoke_guild_active', table_name='karaoke', postgresql_where=sa.text("state <> 'finished'"))
    op.drop_table('karaoke')
    op.drop_table('guildpermissionsconfig')
    op.drop_table('guildkaraokeconfig')
    # ### end Alembic commands ###
